// automatically generated by build_post_index.js
export default [
  {
    "filePath": "pages/posts/20191204.mdx",
    "urlPath": "/posts/20191204",
    "title": "testKaTeX",
    "publishDate": "2019-12-04T12:32:49.197Z",
    "keywords": ""
  },
  {
    "filePath": "pages/posts/20191202.mdx",
    "urlPath": "/posts/20191202",
    "title": "準凸最適化問題に対する最適化手法",
    "publishDate": "2019-12-03T08:29:54.121Z",
    "keywords": "quasi-convex,optimization,continuous,準凸最適化,準凸関数,単峰関数,最適化"
  }
]
