// automatically generated by build_post_index.js
export default [
  {
    "filePath": "pages/posts/20200221.mdx",
    "urlPath": "/posts/20200221",
    "title": "標示関数の劣微分と法線錐の関係（凸解析）",
    "publishDate": "2020-02-21T12:29:38.622Z",
    "keywords": "normal cone,法線錐,subdifferential,劣微分,最適性条件,凸解析"
  },
  {
    "filePath": "pages/posts/20191202.mdx",
    "urlPath": "/posts/20191202",
    "title": "準凸最適化問題に対する最適化手法",
    "publishDate": "2019-12-03T08:29:54.121Z",
    "keywords": "quasi-convex,optimization,continuous,準凸最適化,準凸関数,単峰関数,最適化"
  }
]
