// automatically generated by build_post_index.js
export default [
  {
    "filePath": "pages/posts/20191202.mdx",
    "urlPath": "/posts/20191202",
    "title": "準凸最適化問題に対する最適化手法",
    "publishDate": "2019-12-03T08:29:54.121Z"
  }
]
